package input


func defineInsertOps() map[byte]Op {
    return map[byte]Op {
        8: {"BS", BackspaceOp, false},
        9: { "TAB", TabOp, false }, // tab
        10: { "LF", CarryLineOp, false }, // return mac/linux
        // 13: "CR", // return windows
        27: { "ESC", NormalModeOp, false },

        32: { " ", InsertStringOp, false },
        33: { "!", InsertStringOp, false },
        34: { "\"", InsertStringOp, false },
        35: { "#", InsertStringOp, false },
        36: { "$", InsertStringOp, false },
        37: { "%", InsertStringOp, false },
        38: { "&", InsertStringOp, false },
        39: { "'", InsertStringOp, false },
        40: { "(", InsertStringOp, false },
        41: { ")", InsertStringOp, false },
        42: { "*", InsertStringOp, false },
        43: { "+", InsertStringOp, false },
        44: { ",", InsertStringOp, false },
        45: { "-", InsertStringOp, false },
        46: { ".", InsertStringOp, false },
        47: { "/", InsertStringOp, false },

        48: { "0", InsertStringOp, false },
        49: { "1", InsertStringOp, false },
        50: { "2", InsertStringOp, false },
        51: { "3", InsertStringOp, false },
        52: { "4", InsertStringOp, false },
        53: { "5", InsertStringOp, false },
        54: { "6", InsertStringOp, false },
        55: { "7", InsertStringOp, false },
        56: { "8", InsertStringOp, false },
        57: { "9", InsertStringOp, false },

        58: { ":", InsertStringOp, false },
        59: { ";", InsertStringOp, false },
        60: { "<", InsertStringOp, false },
        61: { "=", InsertStringOp, false },
        62: { ">", InsertStringOp, false },
        63: { "?", InsertStringOp, false },
        64: { "@", InsertStringOp, false },

        65: { "A", InsertStringOp, false },
        66: { "B", InsertStringOp, false },
        67: { "C", InsertStringOp, false },
        68: { "D", InsertStringOp, false },
        69: { "E", InsertStringOp, false },
        70: { "F", InsertStringOp, false },
        71: { "G", InsertStringOp, false },
        72: { "H", InsertStringOp, false },
        73: { "I", InsertStringOp, false },
        74: { "J", InsertStringOp, false },
        75: { "K", InsertStringOp, false },
        76: { "L", InsertStringOp, false },
        77: { "M", InsertStringOp, false },
        78: { "N", InsertStringOp, false },
        79: { "O", InsertStringOp, false },
        80: { "P", InsertStringOp, false },
        81: { "Q", InsertStringOp, false },
        82: { "R", InsertStringOp, false },
        83: { "S", InsertStringOp, false },
        84: { "T", InsertStringOp, false },
        85: { "U", InsertStringOp, false },
        86: { "V", InsertStringOp, false },
        87: { "W", InsertStringOp, false },
        88: { "X", InsertStringOp, false },
        89: { "Y", InsertStringOp, false },
        90: { "Z", InsertStringOp, false },

        91: { "[", InsertStringOp, false },
        92: { "\\", InsertStringOp, false },
        93: { "]", InsertStringOp, false },
        94: { "^", InsertStringOp, false },
        95: { "_", InsertStringOp, false },
        96: { "`", InsertStringOp, false },

        97: { "a", InsertStringOp, false },
        98: { "b", InsertStringOp, false },
        99: { "c", InsertStringOp, false },
        100: { "d", InsertStringOp, false },
        101: { "e", InsertStringOp, false },
        102: { "f", InsertStringOp, false },
        103: { "g", InsertStringOp, false },
        104: { "h", InsertStringOp, false },
        105: { "i", InsertStringOp, false },
        106: { "j", InsertStringOp, false },
        107: { "k", InsertStringOp, false },
        108: { "l", InsertStringOp, false },
        109: { "m", InsertStringOp, false },
        110: { "n", InsertStringOp, false },
        111: { "o", InsertStringOp, false },
        112: { "p", InsertStringOp, false },
        113: { "q", InsertStringOp, false },
        114: { "r", InsertStringOp, false },
        115: { "s", InsertStringOp, false },
        116: { "t", InsertStringOp, false },
        117: { "u", InsertStringOp, false },
        118: { "v", InsertStringOp, false },
        119: { "w", InsertStringOp, false },
        120: { "x", InsertStringOp, false },
        121: { "y", InsertStringOp, false },
        122: { "z", InsertStringOp, false },

        123: { "{", InsertStringOp, false },
        124: { "|", InsertStringOp, false },
        125: { "}", InsertStringOp, false },
        126: { "~", InsertStringOp, false },

        127: { "DEL", BackspaceOp, false },
    }
}
