package input

import (
	"github.com/jackitaliano/wayfinder/internal/tui/events"
)


func defineNormalOps() map[byte]events.InputEvent {
    return map[byte]events.InputEvent {
        8: events.NoOpInput("BS"),
        9: events.NoOpInput("TAB"),
        10: events.NoOpInput("LF"), // return mac/linux
        // 13: "CR", // return windows
        27: events.NoOpInput("ESC"),

        32: events.NoOpInput(" "),
        33: events.NoOpInput("!"),
        34: events.NoOpInput("\""),
        35: events.NoOpInput("#"),
        36: events.MoveOpInput("$"),
        37: events.NoOpInput("%"),
        38: events.NoOpInput("&"),
        39: events.NoOpInput("'"),
        40: events.NoOpInput("("),
        41: events.NoOpInput(")"),
        42: events.NoOpInput("*"),
        43: events.NoOpInput("+"),
        44: events.NoOpInput(","),
        45: events.NoOpInput("-"),
        46: events.NoOpInput("."),
        47: events.NoOpInput("/"),

        48: events.MoveOpInput("0"),
        49: events.NoOpInput("1"),
        50: events.NoOpInput("2"),
        51: events.NoOpInput("3"),
        52: events.NoOpInput("4"),
        53: events.NoOpInput("5"),
        54: events.NoOpInput("6"),
        55: events.NoOpInput("7"),
        56: events.NoOpInput("8"),
        57: events.NoOpInput("9"),

        58: events.NoOpInput(":"),
        59: events.NoOpInput(";"),
        60: events.NoOpInput("<"),
        61: events.NoOpInput("="),
        62: events.NoOpInput(">"),
        63: events.NoOpInput("?"),
        64: events.NoOpInput("@"),

        65: events.ChangeModeInput("A"),
        66: events.NoOpInput("B"),
        67: events.NoOpInput("C"),
        68: events.DeleteInput("D"),
        69: events.NoOpInput("E"),
        70: events.NoOpInput("F"),
        71: events.NoOpInput("G"),
        72: events.NoOpInput("H"),
        73: events.ChangeModeInput("I"),
        74: events.NoOpInput("J"),
        75: events.NoOpInput("K"),
        76: events.NoOpInput("L"),
        77: events.NoOpInput("M"),
        78: events.NoOpInput("N"),
        79: events.ChangeModeInput("O"),
        80: events.NoOpInput("P"),
        81: events.NoOpInput("Q"),
        82: events.NoOpInput("R"),
        83: events.NoOpInput("S"),
        84: events.NoOpInput("T"),
        85: events.NoOpInput("U"),
        86: events.NoOpInput("V"),
        87: events.NoOpInput("W"),
        88: events.NoOpInput("X"),
        89: events.NoOpInput("Y"),
        90: events.NoOpInput("Z"),

        91: events.NoOpInput("["),
        92: events.NoOpInput("\\"),
        93: events.NoOpInput("]"),
        94: events.NoOpInput("^"),
        95: events.NoOpInput("_"),
        96: events.NoOpInput("`"),

        97: events.ChangeModeInput("a"),
        98: events.NoOpInput("b"),
        99: events.NoOpInput("c"),
        100: events.NoOpInput("d"),
        101: events.NoOpInput("e"),
        102: events.NoOpInput("f"),
        103: events.NoOpInput("g"),
        104: events.MoveOpInput("h"),
        105: events.ChangeModeInput("i"),
        106: events.MoveOpInput("j"),
        107: events.MoveOpInput("k"),
        108: events.MoveOpInput( "l"),
        109: events.NoOpInput("m"),
        110: events.NoOpInput("n"),
        111: events.ChangeModeInput("o"),
        112: events.NoOpInput("p"),
        113: events.NoOpInput("q"),
        114: events.NoOpInput("r"),
        115: events.NoOpInput("s"),
        116: events.NoOpInput("t"),
        117: events.NoOpInput("u"),
        118: events.NoOpInput("v"),
        119: events.NoOpInput("w"),
        120: events.DeleteInput("x"),
        121: events.NoOpInput("y"),
        122: events.NoOpInput("z"),

        123: events.NoOpInput("{"),
        124: events.NoOpInput("|"),
        125: events.NoOpInput("}"),
        126: events.NoOpInput("~"),

        127: events.NoOpInput("DEL"),
    }
}
