package input


func defineNormalOps() map[byte]Op {
    return map[byte]Op {
        8: {"BS", NoOp, false},
        9: { "TAB", NoOp, false }, // tab
        10: { "LF", NoOp, false }, // return mac/linux
        // 13: "CR", // return windows
        27: { "ESC", NoOp, false },

        32: { " ", NoOp, false },
        33: { "!", NoOp, false },
        34: { "\"", NoOp, false },
        35: { "#", NoOp, false },
        36: { "$", MoveOp, false },
        37: { "%", NoOp, false },
        38: { "&", NoOp, false },
        39: { "'", NoOp, false },
        40: { "(", NoOp, false },
        41: { ")", NoOp, false },
        42: { "*", NoOp, false },
        43: { "+", NoOp, false },
        44: { ",", NoOp, false },
        45: { "-", NoOp, false },
        46: { ".", NoOp, false },
        47: { "/", NoOp, false },

        48: { "0", MoveOp, false },
        49: { "1", NoOp, false },
        50: { "2", NoOp, false },
        51: { "3", NoOp, false },
        52: { "4", NoOp, false },
        53: { "5", NoOp, false },
        54: { "6", NoOp, false },
        55: { "7", NoOp, false },
        56: { "8", NoOp, false },
        57: { "9", NoOp, false },

        58: { ":", NoOp, false },
        59: { ";", NoOp, false },
        60: { "<", NoOp, false },
        61: { "=", NoOp, false },
        62: { ">", NoOp, false },
        63: { "?", NoOp, false },
        64: { "@", NoOp, false },

        65: { "A", ChangeModeOp, false },
        66: { "B", NoOp, false },
        67: { "C", NoOp, false },
        68: { "D", DeleteOp, false },
        69: { "E", NoOp, false },
        70: { "F", NoOp, false },
        71: { "G", NoOp, false },
        72: { "H", NoOp, false },
        73: { "I", ChangeModeOp, false },
        74: { "J", NoOp, false },
        75: { "K", NoOp, false },
        76: { "L", NoOp, false },
        77: { "M", NoOp, false },
        78: { "N", NoOp, false },
        79: { "O", OpenLineOp, false },
        80: { "P", NoOp, false },
        81: { "Q", NoOp, false },
        82: { "R", NoOp, false },
        83: { "S", NoOp, false },
        84: { "T", NoOp, false },
        85: { "U", NoOp, false },
        86: { "V", NoOp, false },
        87: { "W", NoOp, false },
        88: { "X", NoOp, false },
        89: { "Y", NoOp, false },
        90: { "Z", NoOp, false },

        91: { "[", NoOp, false },
        92: { "\\", NoOp, false },
        93: { "]", NoOp, false },
        94: { "^", NoOp, false },
        95: { "_", NoOp, false },
        96: { "`", NoOp, false },

        97: { "a", ChangeModeOp, false },
        98: { "b", NoOp, false },
        99: { "c", NoOp, false },
        100: { "d", NoOp, false },
        101: { "e", NoOp, false },
        102: { "f", NoOp, false },
        103: { "g", NoOp, false },
        104: { "h", MoveOp, false },
        105: { "i", ChangeModeOp, false },
        106: { "j", MoveOp, false },
        107: { "k", MoveOp, false },
        108: { "l", MoveOp, false },
        109: { "m", NoOp, false },
        110: { "n", NoOp, false },
        111: { "o", OpenLineOp, false },
        112: { "p", NoOp, false },
        113: { "q", NoOp, false },
        114: { "r", NoOp, false },
        115: { "s", NoOp, false },
        116: { "t", NoOp, false },
        117: { "u", NoOp, false },
        118: { "v", NoOp, false },
        119: { "w", NoOp, false },
        120: { "x", DeleteOp, false },
        121: { "y", NoOp, false },
        122: { "z", NoOp, false },

        123: { "{", NoOp, false },
        124: { "|", NoOp, false },
        125: { "}", NoOp, false },
        126: { "~", NoOp, false },

        127: { "DEL", NoOp, false },
    }
}
